### ISSUE TITLE
Allow selecting user specific Python installation

### ISSUE THREAD

**Issue by PyPablo** [pyansys/python-installer-qt-gui#57]
### 📝 Description of the feature

For instance, CPython shipped with Ansys under Ansys folder is not detected by the app

**Comment by kmahajan-cadfem** [comment]
Hi @RobPasMue and @abhishekchitwar 

for many customers it is not possible to install python (because of admin rights). 
in those cases, if user wishes to work with PyAnsys, then i think it makes more sense to use the python that is already available on the machine - namely CPython shipped with Ansys.

I do understand that the PyAnsys should not be dependent on Ansys Installations but still the uptake starts with the simulation engineers who already have Ansys installed on their own machine.

so i am voting for this feature.

**Comment by abhishekchitwar** [comment]
@kmahajan-cadfem, 

Thank you for your feedback on the usage of existing python shipped with Ansys Installation. We appreciate your input and are always looking for ways to improve. 

We will definitely take your suggestion into consideration for future development. Thanks!

- Abhishek
